import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../../components/Header";
import Footer from "../../components/Footer";

export default function Works() {
    interface work {
        id: number;
        title: string;
        description: string;
    }
    const works: work[] = [
        {
            id: 1,
            title: "Title of work one",
            description: "And a short descriprion for this work",
        },
        {
            id: 2,
            title: "Title of work two",
            description: "And a short descriprion for this work",
        },
    ];
    return (
        <>
            <Head>
                <title>should-I-know: works</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.svg" />
            </Head>
            <main>
                <Header location="works" />

                <div className="works_list">
                    {works.map((work) => (
                        <div key={work.id}>
                            <Link href={`/works/${work.id}`}>{work.title}</Link>
                            <p>{work.description}</p>
                        </div>
                    ))}
                </div>
                <Footer />
            </main>
        </>
    );
}
