import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../components/Header";
import Footer from "../components/Footer";

export default function About() {
    return (
        <>
            <Head>
                <title>should-I-know: about</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.svg" />
            </Head>
            <Header location="about" />
            <main>
                <div className="spacer_100"></div>
                <div className="main_image_container">
                    <Image
                        src="/works/images/kaleidanceskope_08_web_kuekelhahn.jpg"
                        alt=""
                        fill
                        style={{
                            objectFit: "cover",
                        }}
                    />
                </div>
                <div className="spacer_100"></div>
                <div className="works_main">
                    <div className="work_details">
                        <h2>should-I-know</h2>
                        <p>
                            Tümay Kılınçel und Cornelius Schaper arbeiten seit
                            2014 zusammen und seit 2022 unter dem Namen
                            should-I-know. Ihre Arbeiten umfassen unter anderem
                            kaleiDANCEscope (2022) in Koproduktion mit asphalt
                            Festival und FFT Düsseldorf. 2020/21 waren sie
                            zusammen mit Jungyun Bae Teil des mentoring
                            Programms des LFDK NRW und setzten sich mit „Räumen“
                            auseinander. 2021 hatte sie außerdem eine Residenz
                            an der Herderschule/Mousonturm Frankfurt a.M. inne.
                            2019 und 2020 waren sie Teil der hessischen FLUX
                            Residenzen im ländlichen Raum. Ihre erste Arbeit
                            DANCE BOX (2014) in Koproduktion mit dem FFT und
                            Freischwimmer Festival tourte 3 Jahre durch
                            Deutschland, Österreich und Schweiz. Should-I- know
                            definieren sich durch interdisziplinäres Arbeiten
                            auf Augenhöhe. In ihren gemeinsamen Arbeiten werden
                            vorhandene Strukturen des öffentlichen Raums neu
                            geordnet, umgedeutet und unterwandert: Die
                            Projektideen durchleuchten Wechselwirkungen von
                            Innen und Außen, Privat und Öffentlich, Einschluss
                            und Ausschluss.{" "}
                        </p>
                    </div>

                    <div className="work_dates">
                        <h2>Kontakt</h2>

                        <p>
                            email:
                            <br />
                            info@sould-i-know.de
                        </p>
                        <p>
                            phone:
                            <br />
                            +49 151 55555
                        </p>
                    </div>
                </div>
                <div className="spacer_100"></div>
            </main>
            <Footer />
        </>
    );
}
