import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../components/Header";
import Footer from "../components/Footer";

export default function About() {
    return (
        <>
            <Head>
                <title>should-I-know: about</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.svg" />
            </Head>
            <Header location="about" />
            <main>
                <div className="spacer_100"></div>
                <div className="main_image_container">
                    <Image
                        src="/works/images/kaleidanceskope_08_web_kuekelhahn.jpg"
                        alt=""
                        fill
                        style={{
                            objectFit: "cover",
                        }}
                    />
                </div>
                <div className="spacer_100"></div>
                <div className="works_main">
                    <div className="work_details">
                        <h2>should-I-know</h2>
                        <p>
                            Tümay Kılınçel und Cornelius Schaper nennen sich
                            zusammen should-I-know. Als Duo arbeiten sie
                            gemeinsam an Projekten im Bereich von Kunst und
                            Kultur. Wichtig ist ihnen immer einen Bezug zum Raum
                            und der Öffentlichkeit zu haben. Als should-I-know
                            möchten sie nämlich mit ihren Arbeiten nicht nur im
                            Theater zu sehen sein, sondern gehen auch zu den
                            Menschen. Hier kann Austausch nochmal anders
                            stattfinden – ganz direkt. <br />
                            <br />
                            Tümay Kılınçel hat in Berlin und Gießen
                            zeitgenössischen Tanz, Kontext Choreografie und
                            Performance studiert. Seitdem macht sie
                            unterschiedliche Arbeiten auf und hinter der Bühne.{" "}
                            <br />
                            <br />
                            Cornelius Schaper beschäftigt sich mit Video und
                            Performance. Er macht Video-Installationen und
                            arbeitet als Dramaturg und in anderen Positionen im
                            Bereich der performativen Arbeit.
                            <br />
                            <br />
                            Die beiden arbeiten seit vielen Jahren zusammen,
                            manchmal auch mit anderen Künstler*innen.{" "}
                        </p>
                    </div>

                    <div className="work_dates">
                        <h2>Kontakt</h2>

                        <p>
                            email:
                            <br />
                            info@sould-i-know.de
                        </p>
                        <p>
                            phone:
                            <br />
                            +49 151 55555
                        </p>
                    </div>
                </div>
                <div className="spacer_100"></div>
            </main>
            <Footer />
        </>
    );
}
