import Head from "next/head";
import Link from "next/link";

import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Home() {
    return (
        <>
            <Head>
                <title>should-I-know</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <img
                    className="hero_background"
                    src="/statics/hero.jpg"
                    alt=""
                />
                <div className="hero">
                    <div className="hero_txt">
                        <h1>
                            should-
                            <br />
                            I-know
                        </h1>
                    </div>
                    <Footer />
                </div>
            </main>
        </>
    );
}
